# Generated by Django 5.1.15 on 2026-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(default='Credit Card / Secure Checkout', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='Standard Priority Shipping', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('processing', 'Processing Order'), ('shipped', 'Shipped / Dispatched'), ('delivered', 'Delivered & Signed'), ('cancelled', 'Order Cancelled')], default='processing', max_length=30),
        ),
    ]
