# Generated by Django 5.1.15 on 2026-07-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('2FA_VERIFIED', '2FA Verified'), ('ORDER_PLACED', 'Order Placed'), ('INVENTORY_ALERT', 'Inventory Alert'), ('SECURITY_VIOLATION', 'Security Violation')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Enterprise Audit Log',
                'verbose_name_plural': 'Enterprise Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
