# Generated by Django 5.1.15 on 2026-07-04 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off ($)'), ('free_shipping', 'Free VIP Express Shipping')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(default=100)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_balance', models.PositiveIntegerField(default=500, help_text='100 points = $10 Enterprise Credit')),
                ('lifetime_points', models.PositiveIntegerField(default=500)),
                ('tier_level', models.CharField(default='Gold VIP Wholesale', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title tag (60 chars max recommended)', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Meta description (160 chars max recommended)')),
                ('og_image_url', models.URLField(blank=True, help_text='OpenGraph image URL', max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promotions/flash/')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('discount_percentage', models.PositiveSmallIntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(related_name='flash_sales', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
