# Generated by Django 5.1.15 on 2026-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off ($)'), ('free_shipping', 'Free Priority Shipping')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='loyaltypoint',
            name='points_balance',
            field=models.PositiveIntegerField(default=500, help_text='100 points = $10 Store Credit'),
        ),
        migrations.AlterField(
            model_name='loyaltypoint',
            name='tier_level',
            field=models.CharField(default='Gold Tier Customer', max_length=50),
        ),
    ]
