# Generated by Django 5.1.15 on 2026-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'System Superadmin'), ('brand_partner', 'Brand Partner'), ('store_manager', 'Store Manager'), ('customer', 'Customer')], default='customer', max_length=30),
        ),
    ]
