# Generated by Django 5.1.15 on 2026-07-04 13:57

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title tag (60 chars max recommended)', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Meta description (160 chars max recommended)')),
                ('og_image_url', models.URLField(blank=True, help_text='OpenGraph image URL', max_length=500)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='catalog/brands/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title tag (60 chars max recommended)', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Meta description (160 chars max recommended)')),
                ('og_image_url', models.URLField(blank=True, help_text='OpenGraph image URL', max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('bundle_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percentage', models.PositiveSmallIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='catalog/products/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_suffix', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, help_text='e.g. Cyber Black, Quantum Silver', max_length=50)),
                ('size', models.CharField(blank=True, help_text='e.g. 1U Blade, 4U Rack, 64-Core', max_length=50)),
                ('material', models.CharField(blank=True, help_text='e.g. Titanium Alloy, Copper Shielding', max_length=50)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title tag (60 chars max recommended)', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Meta description (160 chars max recommended)')),
                ('og_image_url', models.URLField(blank=True, help_text='OpenGraph image URL', max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('icon_class', models.CharField(blank=True, default='bi-cpu-fill', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title tag (60 chars max recommended)', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Meta description (160 chars max recommended)')),
                ('og_image_url', models.URLField(blank=True, help_text='OpenGraph image URL', max_length=500)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=10)),
                ('low_stock_threshold', models.PositiveIntegerField(default=3)),
                ('short_description', models.CharField(max_length=500)),
                ('rich_description', models.TextField()),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Key-value specifications grid')),
                ('has_360_viewer', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('download_manual_url', models.URLField(blank=True, max_length=500)),
                ('rating_average', models.DecimalField(decimal_places=2, default=4.9, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
