# Generated by Django 5.1.15 on 2026-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, help_text='e.g. Matte Black, FDE Flat Dark Earth, OD Green', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='material',
            field=models.CharField(blank=True, help_text='e.g. 7075-T6 Aluminum, AR500 Steel, Kevlar / PE', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, help_text='e.g. 16" Barrel, 30-Round, Large / SAPI', max_length=50),
        ),
    ]
