# Generated by Django 5.1.15 on 2026-07-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, default='bi-shield-check', max_length=100),
        ),
    ]
