# Generated by Django 5.1.15 on 2026-07-11 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_description_alter_category_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schematic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title tag (60 chars max recommended)', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Meta description (160 chars max recommended)')),
                ('og_image_url', models.URLField(blank=True, help_text='OpenGraph image URL', max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('manufacturer_name', models.CharField(blank=True, help_text="Used if Brand object doesn't exist", max_length=150)),
                ('schematic_id_number', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='catalog/schematics/')),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schematics', to='catalog.brand')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SchematicPart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagram_number', models.CharField(help_text='The number/letter on the diagram (e.g. 21, 10A)', max_length=20)),
                ('part_name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(blank=True, help_text='Link to a store product if available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schematic_references', to='catalog.product')),
                ('schematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='catalog.schematic')),
            ],
            options={
                'ordering': ['diagram_number'],
            },
        ),
    ]
