# Generated by Django 5.1.15 on 2026-07-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_schematic_schematicpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='schematic',
            name='category_name',
            field=models.CharField(blank=True, help_text="Grouping header under the brand, e.g. 'Rifles' or 'Handguns'", max_length=150),
        ),
    ]
