# Generated by Django 5.1.15 on 2026-07-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_schematic_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerTimesVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trigger Times Video',
                'verbose_name_plural': 'Trigger Times Videos',
                'ordering': ['-date_published'],
            },
        ),
    ]
