# Generated by Django 5.1.15 on 2026-07-12 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_triggertimesvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(help_text='The URL to scrape (e.g. Trigger Times page)', max_length=500)),
                ('target_category', models.CharField(help_text="Category slug to store results (e.g. 'rifle-builds')", max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('logs', models.TextField(blank=True, help_text='Background logs and output from the scraping process')),
            ],
            options={
                'verbose_name': 'Scraper Task',
                'verbose_name_plural': 'Scraper Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
