# Generated by Django 5.1.15 on 2026-07-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_scrapertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapertask',
            name='task_type',
            field=models.CharField(choices=[('trigger_times', 'Trigger Times Videos'), ('products', 'Product Catalog')], default='trigger_times', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapertask',
            name='source_url',
            field=models.URLField(blank=True, help_text='The URL to scrape (if applicable)', max_length=500),
        ),
        migrations.AlterField(
            model_name='scrapertask',
            name='target_category',
            field=models.CharField(blank=True, help_text='Category slug to store results (if applicable)', max_length=100),
        ),
    ]
