# Generated by Django 5.1.15 on 2026-07-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_scrapertask_task_type_alter_scrapertask_source_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapertask',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='scrapertask',
            name='target_category',
        ),
        migrations.RemoveField(
            model_name='scrapertask',
            name='task_type',
        ),
        migrations.AddField(
            model_name='scrapertask',
            name='from_url',
            field=models.URLField(blank=True, help_text='The URL to start scraping from', max_length=500),
        ),
        migrations.AddField(
            model_name='scrapertask',
            name='to_url',
            field=models.URLField(blank=True, help_text='The URL to end scraping (optional)', max_length=500),
        ),
    ]
