# Generated by Django 5.1.15 on 2026-07-17 07:30

from django.db import migrations


def copy_categories(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for product in Product.objects.all():
        if product.category:
            product.categories.add(product.category)

def reverse_categories(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for product in Product.objects.all():
        if product.categories.exists():
            product.category = product.categories.first()
            product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_categories_alter_product_category'),
    ]

    operations = [
        migrations.RunPython(copy_categories, reverse_categories),
    ]
